version: "3.9"

services:
  web:
    build: .
    container_name: urban_web
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    environment:
      - DJANGO_DEBUG='True'
    env_file:
      - ./.env_dep
    entrypoint: /entrypoint.sh
  bot:
    build: .
    container_name: urban_bot
    command: python run_pooling.py
    volumes:
      - .:/code
    env_file:
      - ./.env_dep
    depends_on:
      - web
